
version: 0.2
env:
  variables:
    ACCEPT_HIGHCHARTS_LICENSE: "YES"
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run deploy
artifacts:
  files:
    - "build/index.js"
    - "node_modules/.bin/phantomjs*"
  